# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
    puts("check for build Fastlane app")
    deliver(
      skip_screenshots: true, #Don't upload the screenshots
      skip_binary_upload: true, #Skip uploading an ipa to iTunes Connect
      force: true #Skip the HTML report file verification
    )
  end

end
